# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75f3a83d515218926c54401d9322272921104b0490c33ac6d2ae285e83119a69e427b1103038d8f6a89c8cc618dd0447a67f56b931ef20a27e450ec58eec42b4

test:
  secret_key_base: dd1c141d02a2199e96b35c02c2b540b2ec3caa131284ba9ed590814c65f2409ed376fb7eeadf1de32c7750b5855fb880f7e83181f3180ca59de709a14e802685

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
